openapi: 3.1.0
info:
  version: 1.0.0
  title: <назва вашого додатку>
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: <опис вашого додатку>
tags:
  - name: Contacts
    description: Contacts operations
servers:
  - url: http://localhost:8080
  - url: https://nodejs-hw-mongodb-yr62.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{contactId}/get.yaml
    delete:
      $ref: ../swagger/paths/contacts/{contactId}/delete.yaml
    patch:
      $ref: ../swagger/paths/contacts/{contactId}/patch.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
